from enum import Enum


class Keys(Enum):
    QUIT = 24
    SAVE = 19
    MOVE_TO_BEGINNING_OF_LINE = 1
    MOVE_TO_END_OF_LINE = 5
    MOVE_FORWARD_ONE_CHARACTER = 6
    MOVE_BACKWARD_ONE_CHARACTER = 2
    MOVE_TO_NEXT_LINE = 14
    MOVE_TO_PREVIOUS_LINE = 16
    BACKSPACE = 263
    NEWLINE = 10
